name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Löst den Workflow aus, wenn ein Tag, der mit "v" beginnt (z. B. v1.0.0), gepusht wird

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: JDK 21 einrichten
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build mit Maven
        run: mvn clean package

      - name: Artifact hochladen
        uses: actions/upload-artifact@v4.6.0
        with:
          name: jar-artifact
          path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Artifact herunterladen
        uses: actions/download-artifact@v4.1.8
        with:
          name: jar-artifact

      - name: GitHub Release erstellen und JAR anhängen
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          artifacts: '*.jar'
          generateReleaseNotes: false
          makeLatest: legacy
          omitBody: false
          omitBodyDuringUpdate: false
          omitDraftDuringUpdate: false
          omitName: false
          omitNameDuringUpdate: false
          omitPrereleaseDuringUpdate: false
          removeArtifacts: false
          replacesArtifacts: true
          skipIfReleaseExists: false
          token: ${{ secrets.RELEASE_TOKEN }}
          updateOnlyUnreleased: false