name: Build JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: JDK 17 einrichten
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build mit Gradle ausführen
        run: ./gradlew clean build

      - name: Erzeugte JAR als Artefakt speichern
        uses: actions/upload-artifact@v3
        with:
          name: generated-jar
          path: build/libs/*.jar
